# Generated by Django 3.1.2 on 2022-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='pwd',
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='signup',
            table=None,
        ),
    ]
