# Generated by Django 3.1.2 on 2022-01-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220119_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='pwd',
        ),
    ]
