# Generated by Django 3.1.2 on 2022-01-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220119_1016'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='student',
        ),
    ]
