# Generated by Django 3.1.2 on 2022-01-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220119_1031'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='student_signup',
        ),
    ]
