# Generated by Django 3.1.2 on 2022-01-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20220119_1058'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='student_signup',
        ),
    ]
