# Generated by Django 3.1.2 on 2022-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20220119_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
